version: '3'

services:
  # Application
  database:
    image: 'bitnami/mysql'
    container_name: 'mysql-${APP_NAME}'
    ports:
      - '${DATABASE_PORT}:3307'
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASS}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - 'mysql_data:/bitnami/mysql'
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  mysql_data:
    driver: local
