version: '3'

services:
  # Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'app-${APP_NAME}'
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASS}
    depends_on:
      - database
    networks:
      - app-net
    env_file:
      - .env

  # Database
  database:
    image: 'bitnami/mysql:latest'
    container_name: 'mysql-${APP_NAME}'
    ports:
      - '${DATABASE_PORT}:3306'
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASS}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - 'mysql_data:/bitnami/mysql'
    networks:
      - app-net
    env_file:
      - .env

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: 'grafana-${APP_NAME}'
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - 'grafana_data:/var/lib/grafana'
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  grafana_data:
    driver: local
