name: e2e Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run e2e Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: bitnami/mysql
        env:
          MYSQL_DATABASE: app
          MYSQL_USER: docker
          MYSQL_PASSWORD: docker
          MYSQL_ROOT_PASSWORD: toor
        ports:
          - 3306:3306
        volumes:
          - mysql:/var/lib/mysql
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@v1

      - name: Run Tests
        run: yarn test:e2e
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: ${{ job.services.mysql.ports[3306] }}
          DATABASE_USER: root
          DATABASE_PASS: toor
          JWT_PUBLIC_KEY: ${{secrets.JWT_DUMMY_PUBLIC}}
          JWT_SECRET_KEY: ${{secrets.JWT_DUMMY_PRIVATE}}
